[build]
builder = "NIXPACKS"

[phases.build]
commands = ["pip install -r requirements.txt"]

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[build.env]
NIXPACKS_PYTHON_VERSION = "3.9"
